### ISSUE TITLE
angular-ziggeo hangs protractor e2e tests

### ISSUE THREAD

**Issue by trycatchal** [Ziggeo/angular-ziggeo#11]
hi.

it appears angular-ziggeo isn't test friendly.  in my app i've had to feature-flag ziggeo stuff out so that protractor doesn't get stuck.

I believe the root cause is that ziggeo is being initialized within the angular zone, and so testability never stabilizes.  I'll submit a PR to demonstrate.

**Comment by sambua** [comment]
Closed based on #12 PR
