### ISSUE TITLE
3 things

### ISSUE THREAD

**Issue by trycatchal** [Ziggeo/angular-ziggeo#17]
1. ziggeo-client-sdk is now a normal dependency and not a peer dependency, so the docs need to be corrected.  Also, because of this the angular 5 demo project doesn't work now.  It needs to be removed from package.json, and .angular-cli.json needs to be updated to the right path.
2. Please release the updated version on master so I don't have to point to a commit in package.json ;)
3. webrtc_streaming option seems to now be broken.  When using a server-auth key it verifies forever and eventually says "sorry something went wrong" and fails.  I've been able to reproduce this even on the angular-ziggeo-demo app.

**Comment by sambua** [comment]
Hello @captaincaius ,

Will make required changes on first 2 items. Regarding 3rd item, could you please share configuration options so we could reproduce it from our side?

Thanks

**Comment by sambua** [comment]
Hello @captaincaius ,

Could you please confirm that this bug happens with FF v63? From our side, we could reproduce this bug only with a mentioned browser.

In other browsers seems it works as expected. Seems exact FF version has this bug. Or if it's another browser please advice.

Thanks in advance.

**Comment by trycatchal** [comment]
Hi.  Actually I've seen it on both FF and chrome, so it doesn't seem browser-related.

It's sometimes hard to reproduce, but once it starts it doesn't go away :D

**Comment by trycatchal** [comment]
I took care of point number 1 in both this project and angular-ziggeo-demo with PRs
