### ISSUE TITLE
Library not compatible with Angular 9/Ionic 5

### ISSUE THREAD

**Issue by sagrawal31** [Ziggeo/angular-ziggeo#25]
## Description

I'm trying to use this library with an `Angular 9/Ionic 5` app. When I'm injecting `ZiggeoModule` in one of the app's module, it's failing with something like:

![image](https://user-images.githubusercontent.com/1804514/75425001-d055aa00-5967-11ea-9add-8a50a73b70fd.png)

It says, `ERROR in node_modules/angular-ziggeo/build/ziggeo/modules/ziggeo.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AssessmentTestModule, but could not be resolved to a NgModule class`.

This has to do something with `ivy` & `aot` (which I couldn't figure out). Although, I tried & read various issues related to this:

1. https://github.com/angular/angular/issues/35399
2. https://github.com/angular/angular/issues/35255

## Ionic Environment

```
Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.900.1
   @angular-devkit/schematics    : 9.0.1
   @angular/cli                  : 9.0.3
   @ionic/angular-toolkit        : 2.1.2

System:

   Android SDK Tools : 26.1.1 (/Users/shashank/Library/Android/sdk)
   NodeJS            : v10.16.0 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Catalina
```

## Angular Environment

```
Angular CLI: 9.0.3
Node: 10.16.0
OS: darwin x64

Angular: 9.0.0
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.3
@angular/fire                     5.4.2
@ngtools/webpack                  9.0.1
@schematics/angular               8.3.25
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```

**Comment by sagrawal31** [comment]
I tried to upgrade the library to Angular 9 https://github.com/Ziggeo/angular-ziggeo/compare/master...sagrawal31:ng9?expand=1 but got stuck at some point and unable to give further time to this.

**Comment by sagrawal31** [comment]
Any update here, guys?

**Comment by sambua** [comment]
Hello @sagrawal31 will look this week again, before had difficulties with upgrading Angular version.

**Comment by sagrawal31** [comment]
Thank you, @sambua 

Let me know if I can be of any help.

**Comment by sambua** [comment]
thanks a lot @sagrawal31, very very appreciate 🙂

**Comment by sagrawal31** [comment]
Thanks, @sambua 

Here are my commits of the attempt I made previous https://github.com/sagrawal31/angular-ziggeo/commits/ng9 (in case it helps).

**Comment by sambua** [comment]
hello @sagrawal31 , when you have time could you please test out new version `angular-ziggeo@3.0.1` ?

**Comment by sagrawal31** [comment]
HI @sambua I'll check it today itself.

**Comment by sambua** [comment]
Hello @sagrawal31 ,

Could you please advice if had a chance to check it ? If it's OK, I will close an issue.

**Comment by sagrawal31** [comment]
Hi @sambua, didn't get a chance yet. Let me try right now.

**Comment by sagrawal31** [comment]
@sambua I just tried the video player in one of my Angular 9 app and good news that is just worked fine. Thanks a lot for your effort. 

I think we can close this issue now.

**Comment by sagrawal31** [comment]
One thing, which is not related to this issue. As of now, we need to add the `ziggeo.js` & `ziggeo.scss` that means it gets bundled in the main file required to launch the Angular app. Which is in-efficient. 

Because I might not need those two files in every page but only required in a few components. And since Angular is built with complete lazy-loading & modular style, a similar thing needs to be present here.

Please share your thoughts on this!

**Comment by sambua** [comment]
Hi @sagrawal31 thanks for your testing and share experience, will look is it possible to load css/js in one package.

**Comment by sagrawal31** [comment]
Sure @sambua I'll be waiting to hear back from you. Should we create a separate issue for this?

**Comment by sambua** [comment]
Yes, please if possible create a new one, if someone check not to see that has Angular 9 capability issue :)
