### ISSUE TITLE
How to refresh video player with new video Token

### ISSUE THREAD

**Issue by GobindGupta** [Ziggeo/angular-ziggeo#31]
I am integrating video player with Angular 9.
I have a multiple videos of a user and want to show in video player one by one with button click.
I am not able to update the video player with new video using button click.
Please suggest some way to resolve this.

**Comment by Bane-D** [comment]
Hi there,

This would generally depend on what your on click event handler is doing.

I am presuming that you have an element where you will show the player and the button would be something like a next and previous video button. Now what I would suggest is to have a function that removes the video player and another that creates a new video player.

On this next video button you would just call both and pass the video token.

This can really be done any way you like using pure JS or Angular methods.

Regards,
Bane

**Comment by rahulsharma991** [comment]
Hi there,
My video api token auto generate after some days why this is happen and how i can get a static api token.

**Comment by ntshcalleia** [comment]
Hi @rahulsharma991, can you please contact our support team at support@ziggeo.com with the token you’re referring to and where you found it? We don’t change the tokens of existing videos nor the api token (unless the client manually regenerates api keys on the application settings page).

**Comment by rahulsharma991** [comment]
In Quick start i got the unique application token that will automatically generate after some days i want it same.

**Comment by ntshcalleia** [comment]
Hi @rahulsharma991, the token generated on the quickstart is temporary and can only be used on the Ziggeo website or localhost. You also won't have access to any videos that are recorded using that token. To generate your own static application token you need to start the 30 days free trial by selecting one of our plan options.
