### ISSUE TITLE
Video recorder not working on Mozilla.

### ISSUE THREAD

**Issue by VNithin-Augment** [Ziggeo/angular-ziggeo#8]
Can you mention if there is any new update for this issue.

**Comment by sambua** [comment]
Hello @VNithin-Augment 

Could you please upgrade to latest version `angular-ziggeo@1.0.1`?

Thanks and have a good coding 🙂

**Comment by VNithin-Augment** [comment]
I am already on this version

Versions:
angular-ziggeo: "1.0.1",
ziggeo-client-sdk: 2.31.2

Error log:
Uncaught (in promise): TypeError: Argument 1 is not valid for any of the 1-argument overloads of URL.createObjectURL

**Comment by sambua** [comment]
@VNithin-Augment 

Please replace `"ziggeo-client-sdk": "~2.32.1"` version.  Also, upgrade to `angular-ziggeo@1.0.2`

Thanks

**Comment by sambua** [comment]
fixed with #9

**Comment by sambua** [comment]
fixed with #9
